"""
Константы верстки PDF.

Собираем параметры layout в одном месте, чтобы убрать магические числа из pdf_builder.py.
"""

from __future__ import annotations

# Page margins (mm)
PAGE_MARGIN_LEFT_MM = 15
PAGE_MARGIN_RIGHT_MM = 15
PAGE_MARGIN_TOP_MM = 15
PAGE_MARGIN_BOTTOM_MM = 25

# Frame paddings (pt)
FRAME_PADDING = 0

# Header block
HEADER_ROW_HEIGHT = 20
HEADER_FONT_SIZE = 16
HEADER_UNDERLINE_WIDTH = 2.0

# Parties block
PARTIES_LABEL_COL_MM = 23
PARTIES_FONT_SIZE = 10
PARTIES_ROW_TOP_PADDING = 2
PARTIES_ROW_BOTTOM_PADDING = 2
PARTIES_SPACER_BEFORE = 10
PARTIES_SPACER_AFTER_MM = 4

# Totals block
TOTAL_TABLE_LABEL_COL_MM = 155
TOTAL_FONT_SIZE = 10
TOTAL_ROW_TOP_PADDING = 2
TOTAL_ROW_BOTTOM_PADDING = 2
TOTAL_SPACER_AFTER_MM = 5

# Summary block
SUMMARY_BASE_FONT_SIZE = 10
SUMMARY_AMOUNT_LEADING = 12
SUMMARY_TABLE_FONT_SIZE = 9
SUMMARY_ROW_TOP_PADDING = 2
SUMMARY_ROW_BOTTOM_PADDING = 2
SUMMARY_SPACER_AFTER_MM = 10

# Signatures block
SIGNS_SPACER_BEFORE_MM = 6
SIGNS_FONT_SIZE = 10
SIGNS_ROW_TOP_PADDING = 2
SIGNS_ROW_BOTTOM_PADDING = 2

# Items table block
ITEMS_CARGO_FONT_SIZE = 10
ITEMS_CARGO_LEADING = 11
ITEMS_COL_BASE_WIDTHS = [55, 20, 16, 16, 16, 26, 26]
ITEMS_GRID_WIDTH = 0.5
ITEMS_BOX_WIDTH = 1.5
ITEMS_ROW_TOP_PADDING = 6
ITEMS_ROW_BOTTOM_PADDING = 6
ITEMS_HEADER_TOP_PADDING = 11
ITEMS_HEADER_BOTTOM_PADDING = 11
ITEMS_SPACER_AFTER_MM = 4

# Double-copy mode
CUT_LINE_COLOR_HEX = "#999999"
CUT_LINE_WIDTH = 0.6
CUT_LINE_DASH_ON = 3
CUT_LINE_DASH_OFF = 3
CUT_LINE_OFFSET_MM = 5

# Colors
TABLE_HEADER_BG_HEX = "#ffffff"

